name: Update Ping Schedule

on:
  # Permite você ajustar o cron pela UI em Actions → Update Ping Schedule → Run workflow
  workflow_dispatch:
    inputs:
      cron:
        description: 'Nova expressão cron (mínimo de 5 em 5 minutos)'
        default: '*/5 * * * *'
        required: true

jobs:
  update-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ajustar cron do ping-supabase.yml
        uses: peter-evans/set-cron-schedule@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-file-name: ping-supabase.yml
          schedule: ${{ github.event.inputs.cron }}
